name: Build and test [PostgreSQL]
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
          if: success()

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            coverage: pcov

      -   name: Setup
          if: success()
          run: |
            php -v
            composer install --no-interaction
            touch coverage.xml
            mv .env.postgresql .env

      - uses: harmon758/postgresql-action@v1
        name: Setup postgreSQL
        with:
          postgresql version: '11'
          postgresql user: root
          postgresql password: root
          postgresql db: eloquentdocs

      -   name: PHPUnit tests
          if: success()
          run: |
            composer test